server:
  port: 8080
  forward-headers-strategy: NONE
spring:
  main:
    banner-mode: "off"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://<postgres-server>:5432/<database>?sslmode=verify-full&sslrootcert=/postgresql.crt
#    The following JDBC URL works:
#    url: jdbc:postgresql://<postgres-server>:5432/<database>?sslmode=require
    username: <UAMI-name>
    azure:
      passwordless-enabled: true
    hikari:
      connectionTimeout: 5000
logging:
  level:
    root: ERROR
management:
  endpoint:
    health:
      probes:
        enabled: true
