server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://<postgres-server>:5432/<database>?sslmode=verify-full&sslrootcert=/postgresql.crt
#    The following JDBC URL works:
#    url: jdbc:postgresql://<postgres-server>:5432/<database>?sslmode=require
    username: <UAMI-name>
    azure:
      passwordless-enabled: true
